### ISSUE TITLE
failed to build custom distro with mender enabled

### ISSUE THREAD

**Issue by hesmar** [OE4T/tegra-demo-distro#232] opened 2022-11-03 12:11 UTC
Hi, I created a custom distro layer using the `create-distro-layer` script:
```
> ./scripts-setup/create-distro-layer -d my-mender -m
```
After that, I tried to build an image using this distro:
```
> . ./setup-env -m jetson-nano-devkit-emmc -d my-mender build-my-mender
> bitbake core-image-minimal
```
Bitbake gives me the following error:
```
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
ERROR: Configuration has been re-parsed over 20 times, breaking out of the loop...
ERROR: Error parsing configuration files
Traceback (most recent call last):
  File "/home/hesmar/Development/3dvisionlabs/embedded/yocto2/tegra-demo-distro/repos/poky/bitbake/lib/bb/cookerdata.py", line 281, in CookerDataBuilder.parseBaseConfiguration(worker=False):
                                      "breaking out of the loop...")
    >                    raise Exception("Too deep config re-parse loop. Check locations where "
                                         "BB_INVALIDCONF is being set (ConfigParsed event handlers)")
Exception: Too deep config re-parse loop. Check locations where BB_INVALIDCONF is being set (ConfigParsed event handlers)
```

If I create the distro without Mender (removing the `-m` argument), bitbake works fine. How can I make it work with Mender support enabled?

**Comment by ichergui** [comment] 2022-11-03 12:41
Hello @hesmar 

Please check you `BBLAYERS_CONF_VERSION`

**Comment by dwalkes** [comment] 2022-11-03 13:49
Which branch?  This sequence worked for me on dunfell.

**Comment by hesmar** [comment] 2022-11-03 14:20
I am on `kirkstone-l4t-r32.7.x`.

@ichergui This is the `bblayers.conf`:

```
# Version of layers configuration, specific to
# each defined distro in the repository.
# Format: ${DISTRO}-<version>
TD_BBLAYERS_CONF_VERSION = "my-mender-7"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/hesmar/Development/3dvisionlabs/embedded/yocto2/tegra-demo-distro/layers/meta \
  /home/hesmar/Development/3dvisionlabs/embedded/yocto2/tegra-demo-distro/layers/meta-tegra \
  /home/hesmar/Development/3dvisionlabs/embedded/yocto2/tegra-demo-distro/layers/meta-tegra/contrib \
  /home/hesmar/Development/3dvisionlabs/embedded/yocto2/tegra-demo-distro/layers/meta-oe \
  /home/hesmar/Development/3dvisionlabs/embedded/yocto2/tegra-demo-distro/layers/meta-python \
  /home/hesmar/Development/3dvisionlabs/embedded/yocto2/tegra-demo-distro/layers/meta-networking \
  /home/hesmar/Development/3dvisionlabs/embedded/yocto2/tegra-demo-distro/layers/meta-filesystems \
  /home/hesmar/Development/3dvisionlabs/embedded/yocto2/tegra-demo-distro/layers/meta-virtualization \
  /home/hesmar/Development/3dvisionlabs/embedded/yocto2/tegra-demo-distro/layers/meta-tegra-community \
  /home/hesmar/Development/3dvisionlabs/embedded/yocto2/tegra-demo-distro/layers/meta-mender-core \
  /home/hesmar/Development/3dvisionlabs/embedded/yocto2/tegra-demo-distro/layers/meta-mender-tegra \
  /home/hesmar/Development/3dvisionlabs/embedded/yocto2/tegra-demo-distro/layers/meta-tegra-support \
  /home/hesmar/Development/3dvisionlabs/embedded/yocto2/tegra-demo-distro/layers/meta-demo-ci \
  /home/hesmar/Development/3dvisionlabs/embedded/yocto2/tegra-demo-distro/layers/meta-my-mender \
  "

```

**Comment by dwalkes** [comment] 2022-11-03 16:57
I can reproduce.

I think the problem is at https://github.com/OE4T/tegra-demo-distro/blob/4f6b3291e07f51e94025348a8dfcc0ea924b03b6/scripts-setup/create-distro-layer#L79-L81 which is only appending to the `distro.conf` file but not updating `REQUIRED_TD_BBLAYERS_CONF_VERSION`.  I'm not sure why it's doing the append as opposed to just copying the tegrademo-mender.conf from [conf/distro/tegrademo-mender.conf](https://github.com/OE4T/tegra-demo-distro/blob/kirkstone-l4t-r32.7.x/layers/meta-tegrademo/conf/distro/tegrademo-mender.conf) as the distro default.

When I did that by hand using
```
cp layers/meta-tegrademo/conf/distro/tegrademo-mender.conf layers/meta-my-mender/conf/distro/my-mender.conf
```
I got past this error, then hit:
```
ERROR: ParseError at /home/dan/tegra-demo-distro/layers/meta-tegrademo/conf/distro/tegrademo.conf:34: Could not include required file conf/include/gstreamer-1.14.conf
```

Not sure where this is coming from - I see this file at 
```
 find . -name "gstreamer-1.14.conf"
./repos/meta-tegra/contrib/conf/include/gstreamer-1.14.conf
```
and I see the corresponding layer in `bblayers.conf`
```
TD_BBLAYERS_CONF_VERSION = "my-mender-7"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/dan/tegra-demo-distro/layers/meta \
  /home/dan/tegra-demo-distro/layers/meta-tegra \
  /home/dan/tegra-demo-distro/layers/meta-tegra/contrib \
```

I removed the `require conf/include/gstreamer-1.14.conf` line and started the build, then added it back to attempt to reproduce but could not.

**Comment by hesmar** [comment] 2022-11-08 09:36
Ok, it also helps to apply the following change in the `layers/meta-my-mender/conf/distro/my-mender.conf` after using the `create-distro-layer` script:
```
REQUIRED_TD_BBLAYERS_CONF_VERSION = "${DISTRO}-7"
```

**Comment by ichergui** [comment] 2022-11-08 10:12
That's was my suggestion :wink: earlier

**Comment by ichergui** [comment] 2022-11-08 10:53
@dwalkes Any action from our side ?  otherwise I will close this issue

**Comment by madisongh** [comment] 2022-11-08 13:44
Sounds like the create-distro-layer script needs a fix.

**Comment by ichergui** [comment] 2022-11-08 13:51
Okay
I or @dwalkes will take it

**Comment by dwalkes** [comment] 2022-11-08 14:52
I've got some hacks in https://github.com/OE4T/tegra-demo-distro/pull/233 which I think will fix it.

**Comment by ichergui** [comment] 2023-02-25 12:31
I'm closing this issue since there is a fix already merged.

**Closed by ichergui** 2023-02-25 12:31 UTC
